spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1eezv271x2qwencao.mysql.rds.aliyuncs.com:3306
    username: gxk
    password: Gxk19990805
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    timeout: 5000

logging:
  level:
    root: info

server:
  port: 8080

forest:
  ## 日志总开关，打开/关闭Forest请求/响应日志（默认为 true）
  log-enabled: false
  ## 打开/关闭Forest请求日志（默认为 true）
  log-request: false
  ## 打开/关闭Forest响应状态日志（默认为 true）
  log-response-status: false
  ## 打开/关闭Forest响应内容日志（默认为 false）
  log-response-content: false

  timeout: 10000
  # 全局自动重定向开关，默认为开启
  auto-redirection: false
  interceptors: # 可配置1到多个拦截器


  # 通过 forest.success-when 属性配置全局请求成功/失败条件类
  success-when:
    com.abocidee.servlet.tools.MySuccessCondition
